apiVersion: v1
kind: Service
metadata:
  labels:
    app: chaosblade-box-mysql
  name: chaosblade-box-mysql
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: chaosblade-box-mysql
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chaosblade-box
  name: chaosblade-box
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 7001
      targetPort: 7001
  selector:
    app: chaosblade-box
  sessionAffinity: None
  type: LoadBalancer
